FROM node:4.3

ENV TERRAFORM_VERSION 0.8.1

RUN apt-get update && \
  apt-get install -y zip unzip && \
  curl -Lo /terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" && \
  unzip /terraform.zip -d /bin && \
  rm -rf /var/cache/apk/* /terraform.zip

WORKDIR /usr/src/app
COPY . /usr/src/app
RUN /bin/terraform get
