---
version: "2"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.buildkite
    volumes:
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - TF_VAR_key_name
      - TF_VAR_subnet_ids
      - TF_VAR_vpc_id
      - TF_VAR_internal_elb
      - TF_VAR_cluster_size
      - TF_VAR_access_key
      - TF_VAR_secret_key
      - TF_VAR_region
      - BUILDKITE_S3_ACCESS_KEY_ID
      - BUILDKITE_S3_SECRET_ACCESS_KEY
      - BUILDKITE_S3_DEFAULT_REGION
      - BUILDKITE_S3_ACL
      - BUILDKITE_ARTIFACT_UPLOAD_DESTINATION
      - STATE_BUCKET

  staging:
    extends:
      service: base
    environment:
      APP_ENV: staging

  production:
    extends:
      service: base
    environment:
      APP_ENV: production
