---
version: "2"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.buildkite
    volumes:
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_AGENT_DEBUG
      - BUILDKITE_AGENT_ENDPOINT
      - BUILDKITE_AGENT_META_DATA_DOCKER
      - BUILDKITE_AGENT_META_DATA_ENVIRONMENT
      - BUILDKITE_AGENT_META_DATA_QUEUE
      - BUILDKITE_AGENT_NAME
      - BUILDKITE_AGENT_PID
      - BUILDKITE_ARTIFACT_PATHS
      - BUILDKITE_ARTIFACT_UPLOAD_DESTINATION
      - BUILDKITE_AUTO_SSH_FINGERPRINT_VERIFICATION
      - BUILDKITE_BIN_PATH
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_CHECKOUT_PATH
      - BUILDKITE_BUILD_CREATOR
      - BUILDKITE_BUILD_CREATOR_EMAIL
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_PATH
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMAND
      - BUILDKITE_COMMAND_EVAL
      - BUILDKITE_COMMIT
      - BUILDKITE_HOOKS_PATH
      - BUILDKITE_JOB_ID
      - BUILDKITE_LAST_HOOK_EXIT_STATUS
      - BUILDKITE_MESSAGE
      - BUILDKITE_ORGANIZATION_SLUG
      - BUILDKITE_PIPELINE_PROVIDER
      - BUILDKITE_PIPELINE_SLUG
      - BUILDKITE_PROJECT_PROVIDER
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - BUILDKITE_REPO_SSH_HOST
      - BUILDKITE_RETRY_COUNT
      - BUILDKITE_S3_ACCESS_KEY_ID
      - BUILDKITE_S3_ACL
      - BUILDKITE_S3_DEFAULT_REGION
      - BUILDKITE_S3_SECRET_ACCESS_KEY
      - BUILDKITE_SCRIPT_PATH
      - BUILDKITE_TAG
      - STATE_BUCKET

  staging:
    extends:
      service: base
    environment:
      APP_ENV: staging
    env_file:
      - staging.env

  production:
    extends:
      service: base
    environment:
      APP_ENV: production
    env_file:
      - production.env
